/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'defeatEnemy' : IDL.Func([IDL.Nat], [], []),
  'getGameState' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'enemiesDefeated' : IDL.Nat,
          'score' : IDL.Nat,
          'ammunition' : IDL.Nat,
          'health' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'increaseScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'rechargeWeapon' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'startGame' : IDL.Func([IDL.Nat], [], []),
  'takeDamage' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'defeatEnemy' : IDL.Func([IDL.Nat], [], []),
    'getGameState' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'enemiesDefeated' : IDL.Nat,
            'score' : IDL.Nat,
            'ammunition' : IDL.Nat,
            'health' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'increaseScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'rechargeWeapon' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'startGame' : IDL.Func([IDL.Nat], [], []),
    'takeDamage' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };